### ISSUE TITLE
Incorrect "Tokens for sale" after creating a new STO

### ISSUE THREAD

**Issue by Neopallium** [PolymathNetwork/polymesh-sdk#453]
I couldn't find the repo for the tokenstudio or investor web apps.  If this isn't the correct repo or place to report issues, please let me know.

I have created a few STOs (ids [0](https://itn-investor.polymesh.live/sto/NEOPALLIUM/0), [1](https://itn-investor.polymesh.live/sto/NEOPALLIUM/1), [2](https://itn-investor.polymesh.live/sto/NEOPALLIUM/2)) for token "NEOPALLIUM" on the ITN network.

The tokenstudio shows the correct "Tokens for sale", but the investor portal doesn't.  It looks like the tiers are calculated incorrectly during STO creation.

For example on the [first STO](https://itn-investor.polymesh.live/sto/NEOPALLIUM/0) was created with:
Price: 100 (1 NEOPALLIUM = 100 RWB)
Tokens for Sale: 200 NEOPALLIUM
The tier (or cap) should have been: 200 NEOPALLIUMs * 100 RWB = 20,000 RWB

But instead the investor page is showing:
Tokens for Sale: 2 NEOPALLIUM  (200 NEOPALLIUM / 100 RWB?)
With cap: 200 RWB (this should have been 20,000 RWB).

Here is the "CreateFundraiser" for the first STO:
https://itn-explorer.polymesh.live/polymesh/transaction/678944-2

So it looks like it is a problem calculating the "tier" parameter.

**Comment by VictorVicente** [comment]
Thank you for this! You have described the issue very well,
It seems to be a UI problem from TokenStudio which is already been addressed. Please, try it again soon to check if it is solved, otherwise you could add support ticket on zendesk to follow it up.
